services:
  - type: web
    name: tiktactoe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app 
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false